name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-apple-darwin
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install Zig (for cross-compilation)
        uses: goto-bus-stop/setup-zig@v2

      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild

      - name: Build binary
        run: cargo zigbuild --release --target ${{ matrix.target }}

      - name: Package binary
        run: |
          mkdir output
          cd target/${{ matrix.target }}/release
          bin_name=$(basename $(find . -maxdepth 1 -type f -perm -u+x | head -n 1))
          cp "$bin_name" "../../../output/${{ matrix.target }}-$bin_name"
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-binary
          path: output/*
  
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Zip artifacts
        run: |
          cd dist
          for dir in */ ; do
            zip -r "${dir%/}.zip" "$dir"
          done

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}